export enum ChainId {
    EthereumMainnet = 1,
    Rinkeby = 4,
    Goerli = 5,
    Optimism = 10,
    BSC = 56,
    ETC = 61,
    Aurora = 1313161554,
    Gatechain = 86,
    BSCTestnet = 97,
    AuroraTestnet = 1313161555,
    Heco = 128,
    Matic = 137,
    Fantom = 250,
    Arbitrum = 42161,
    MaticTestnet = 80001,
    Harmony = 1666600000,
    HarmonyTestnet = 1666700000,
    Cronos = 25,
    ZkSyncAlphaTest = 280,
    ZkSyncEra = 324,
    Ontology = 58,
    Ultron = 1231,
    Base = 8453,
    Meter = 82,
    Mantle = 5000,
    Linea = 59144,
    OpBNB = 204,

    MantleTest = 5001,
    ScrollTestL2 = 534353,
    Icplaza = 9000,
    BedrockRolluxTestL2 = 57000,
    ConfluxESpace = 1030,
    LineaTest = 59140,
    OpsideTest = 51178,
    OpBNBTest = 5611,
    KromaSepoliaTest = 2358,
}

export enum TokenSymbol {
    USDC = 'USDC',
    ACY = 'ACY',
    ETH = 'ETH',
    WETH = 'WETH',
    USDT = 'USDT',
    DAI = 'DAI',
    BIT = 'BIT',
    IZI = 'iZi',
    YIN = 'YIN',
    DEVT = 'DEVT',
    DDAO = 'DDAO',
    BNB = 'BNB',
    WBNB = 'WBNB',
    IUSD = 'iUSD',
    APEX = 'APEX',
    BUSD = 'BUSD',
    ESAPEX = 'esAPEX',
    IONS = 'IONS',
    MATIC = 'MATIC',
    swETH = 'swETH',
    SWELL = 'SWELL',
    SLD = 'SLD',
    DUET = 'DUET',
    dWTI = 'dWTI',
    DUSD = 'DUSD',
    USDT18 = 'USDT18',
    KSW = 'KSW',
    REVO = 'REVO',
    LAND = 'LAND',
    FROYO = 'FROYO',
    NAS = 'NAS',
    MNW = 'MNW',
    ARC = 'ARC',
    AURORA = 'AURORA',
    TAP = 'TAP',
    ETC = 'ETC',
    WETC = 'WETC',
    MELT = 'MELT',
    DMT = 'DMT',
    BURGER = 'BURGER',

    // test
    FeeA = 'FeeA',
    FeeB = 'FeeB',
}
